version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - DB_PORT=3306
            - DB_HOST=mysql
            - REDIS_PORT=6379
            - REDIS_HOST=redis
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - DB_PORT=3306
            - DB_HOST=mysql
            - REDIS_PORT=6379
            - REDIS_HOST=redis
        tty: true
    mysql:
        image: mysql:5.7
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - "33061:3306"
        command: '--default-authentication-plugin=mysql_native_password'
    redis:
        image: redis:3.0
        ports:
            - "63791:6379"
    node:
        image: node:8.6-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
    pma:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: pma.local
      ports:
        - 82:80
